---

- name: define distribution-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: perform installation
  include_tasks: install/{{ ansible_os_family }}.yml

- name: configure nginx
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: check whether SSL certificate file exists
  stat: path=/etc/ssl/certs/{{ nginx_cert_name }}.crt
  register: stat_ssl_cert
  when: not nginx_proxy_vhosts

- name: check whether SSL certificate file exists
  stat: path=/etc/ssl/private/{{ nginx_cert_name }}.key
  register: stat_ssl_key
  when: not nginx_proxy_vhosts

- name: fail if either certificate or key do not exist
  fail:
    msg: >
      certificate /etc/ssl/certs/{{ nginx_cert_name }}.crt or key file
      /etc/ssl/private/{{ nginx_cert_name }}.key are missing
  when: >
    not nginx_proxy_vhosts and
    ((not stat_ssl_cert.stat.exists) or (not stat_ssl_key.stat.exists))

- name: create base directory for static HTML pages
  file:
    path: /etc/nginx/static_pages
    state: directory

- name: create directories for static HTML pages
  file:
    path: /etc/nginx/static_pages/{{ item.name }}
    state: directory
  loop: "{{ nginx_static_pages }}"

- name: write out static HTML pages
  copy:
    content: "{{ item.html_content }}"
    dest: /etc/nginx/static_pages/{{ item.name }}/index.html
  loop: "{{ nginx_static_pages }}"

- name: start and enable nginx
  systemd: name=nginx state=started enabled=true
